### PR TITLE
Remove custom error handler

### PR DESCRIPTION
**Pull request by paramaggarwal**
Builds on top of https://github.com/Coly010/no-try/pull/11 to have a simpler and straightforward API. The need for a custom error handler does not exist now that the error object itself is always available on `[error, result]`.

For review, see this commit: https://github.com/Coly010/no-try/pull/12/commits/9318d315323c32ac18c86461b190bf0788da9dc0

Raised this as a separate PR to know your thoughts, if you also feel the same, then will push this commit into the original PR itself. 👍

### CODE REVIEW

**Comment by Coly010** [comment]
I'd rather keep the custom error handling. It's optional so it doesn't need to be used, however, it gives the flexibility of being able to do something like this:

```ts
const [err, res] = noTry(() => myfunc(), logError);

if(err) {
  // perform actions to handle error
}
...

function logError(err) {
    if(!environment.production) {
        console.log("Error", err);
    } else {
       reportErrorToMonitoringService(err);
    }
}
```

In such a away you don't proliferate your business logic with code to log error, making your code both easier to read and remain closer to the context of the business logic at hand.

**Comment by paramaggarwal** [comment]
One of the things I was confused about is whether adding a custom handler consumes it similar to how a normal `.catch()` works in promises and `catch` block of a try/catch. We might need to refer to it as more of a "listener" or "hook" because it doesn't modify the error in any way, just gets a reference to it.

**Comment by Coly010** [comment]
Yes I see what you mean. We may need a docs update to explain it a little better. Perhaps with the use case I've described above added to the README

**Comment by paramaggarwal** [comment]
Let's refer it to a `customLogger` instead of `customHandler` - again to promote good practices as defaults.

**Comment by Coly010** [comment]
No I don't think customLogger is a good name because it's not limited to logging. Perhaps silentHandler or something that represents an unobtrusive / non-consuming handler.

**Comment by paramaggarwal** [comment]
Yeah that's true. Anyways this particular feature might help with readability but it splits the error handling into two parts. 

Typically the handler in `callback(err, res)` used to be to first have an `if(err)` block and they all the error handling inside that and break early if needed and then the rest of the response processing would follow. So the logging can be part of that flow to make it explicit rather than have this disjoint branch. 

Just putting forth my thoughts here.

**Pull request closed without merging**
